# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('testcase1_input', models.TextField()),
                ('testcase2_input', models.TextField()),
                ('testcase3_input', models.TextField()),
                ('testcase1_output', models.TextField()),
                ('testcase2_output', models.TextField()),
                ('testcase3_output', models.TextField()),
                ('test_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choice1', models.CharField(max_length=300)),
                ('choice2', models.CharField(max_length=300)),
                ('choice3', models.CharField(max_length=300)),
                ('choice4', models.CharField(max_length=300)),
                ('correctAnswer', models.IntegerField(default=0)),
                ('test_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestInfo',
            fields=[
                ('test_id', models.IntegerField(primary_key=True, serialize=False)),
                ('faculty_id', models.IntegerField()),
            ],
        ),
    ]
