# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0002_auto_20160226_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQTestAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_ans', models.IntegerField(default=1)),
                ('question_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='testinfo',
            name='test_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mcqtestanswers',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.TestInfo'),
        ),
        migrations.AddField(
            model_name='mcqtestanswers',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.StudentLogin'),
        ),
    ]
