# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0003_auto_20160226_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=10)),
                ('slot', models.CharField(max_length=15)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.FacultyLogin')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=15)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.StudentLogin')),
            ],
        ),
    ]
