# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0004_faculty_subjects_student_faculty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Faculty',
            new_name='Student_Subject',
        ),
    ]
