# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0005_auto_20160226_0144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_subject',
            old_name='username',
            new_name='student_username',
        ),
        migrations.AddField(
            model_name='student_subject',
            name='faculty_username',
            field=models.ForeignKey(default='unassigned', on_delete=django.db.models.deletion.CASCADE, to='Faculty.FacultyLogin'),
            preserve_default=False,
        ),
    ]
